;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        eval-sexp-and-replace
        haskell-mode-contextual-space
        sp-forward-slurp-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        kill-region
        ))
